version: '3.8'
services:
  db:
    image: postgres:15
    container_name: widgets_db
    restart: always
    environment:
      POSTGRES_USER: widgets
      POSTGRES_PASSWORD: widgets
      POSTGRES_DB: widgetsdb
    ports:
      - "5437:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
